version: '3'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    restart: always
  app:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    restart: always
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_HOST: mongodb://mongo_db:27017

volumes:
  mongo_db: {}